# -*- mode: ruby -*-
# vi: set ft=ruby :


servers = [
  {
    :hostname => "example-laravel",
    :ip => "192.168.100.10"
  },
]

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "ubuntu/focal64"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
          vb.memory = 1024
          vb.cpus = 1
      end
      # node setup
      config.vm.provision "file", source: "start-agent.sh", destination: "start-agent.sh"
      config.vm.provision "shell", path: "startup.sh"
    end
  end
end
